/*
 * ManagerFrame.java class that creates manager user interface, no functionality yet
 */
package hms;

/**
 *
 * @author Daniel
 */
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    public ManagerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ManagerMasterView = new javax.swing.JTabbedPane();
        EmployeeView = new javax.swing.JPanel();
        RoomServiceView = new javax.swing.JPanel();
        ConciergeView = new javax.swing.JPanel();
        HouseKeepingView = new javax.swing.JPanel();
        GuestServicesView = new javax.swing.JPanel();
        FrontDeskView = new javax.swing.JPanel();
        LogOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ManagerMasterView.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        EmployeeView.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout EmployeeViewLayout = new javax.swing.GroupLayout(EmployeeView);
        EmployeeView.setLayout(EmployeeViewLayout);
        EmployeeViewLayout.setHorizontalGroup(
            EmployeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        EmployeeViewLayout.setVerticalGroup(
            EmployeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        ManagerMasterView.addTab("Employee View", EmployeeView);

        javax.swing.GroupLayout RoomServiceViewLayout = new javax.swing.GroupLayout(RoomServiceView);
        RoomServiceView.setLayout(RoomServiceViewLayout);
        RoomServiceViewLayout.setHorizontalGroup(
            RoomServiceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        RoomServiceViewLayout.setVerticalGroup(
            RoomServiceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        ManagerMasterView.addTab("Room Service View", RoomServiceView);

        javax.swing.GroupLayout ConciergeViewLayout = new javax.swing.GroupLayout(ConciergeView);
        ConciergeView.setLayout(ConciergeViewLayout);
        ConciergeViewLayout.setHorizontalGroup(
            ConciergeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        ConciergeViewLayout.setVerticalGroup(
            ConciergeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        ManagerMasterView.addTab("Concierge View", ConciergeView);

        javax.swing.GroupLayout HouseKeepingViewLayout = new javax.swing.GroupLayout(HouseKeepingView);
        HouseKeepingView.setLayout(HouseKeepingViewLayout);
        HouseKeepingViewLayout.setHorizontalGroup(
            HouseKeepingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        HouseKeepingViewLayout.setVerticalGroup(
            HouseKeepingViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        ManagerMasterView.addTab("HouseKeeping View", HouseKeepingView);

        javax.swing.GroupLayout GuestServicesViewLayout = new javax.swing.GroupLayout(GuestServicesView);
        GuestServicesView.setLayout(GuestServicesViewLayout);
        GuestServicesViewLayout.setHorizontalGroup(
            GuestServicesViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        GuestServicesViewLayout.setVerticalGroup(
            GuestServicesViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        ManagerMasterView.addTab("Guest Services", GuestServicesView);

        javax.swing.GroupLayout FrontDeskViewLayout = new javax.swing.GroupLayout(FrontDeskView);
        FrontDeskView.setLayout(FrontDeskViewLayout);
        FrontDeskViewLayout.setHorizontalGroup(
            FrontDeskViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        FrontDeskViewLayout.setVerticalGroup(
            FrontDeskViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        ManagerMasterView.addTab("Front Desk View", FrontDeskView);

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManagerMasterView)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LogOutButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManagerMasterView, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ManagerMasterView.getAccessibleContext().setAccessibleName("Room Service View");

        pack();
    }// </editor-fold>                        

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        dispose();
        new HMSFrame().setVisible(true);
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel ConciergeView;
    private javax.swing.JPanel EmployeeView;
    private javax.swing.JPanel FrontDeskView;
    private javax.swing.JPanel GuestServicesView;
    private javax.swing.JPanel HouseKeepingView;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JTabbedPane ManagerMasterView;
    private javax.swing.JPanel RoomServiceView;
    // End of variables declaration                   
}
